management:
  # /actuator/info
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    # /actuator/health
    health:
      show-components: always

  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: ej

# 푸시하기 위해 남기는
# /actuator/loggers
# /actuator/loggers/{로거이름}
logging:
  level:
    com.example.springactuator.controller: debug
